apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkusapp.fullname" . }}
  labels:
    {{- include "quarkusapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if .Values.service.nodeport }}
      nodePort: {{ .Values.service.nodeport }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "quarkusapp.selectorLabels" . | nindent 4 }}